on: pull_request
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 13 Pro Max']
    steps:
      - name: Install tools
        run: brew install xcbeautify

      - name: Checkout
        uses: actions/checkout@master

      - name: Test (Package)
        run: swift test

      - name: Build and test demo app
        run: set -o pipefail && xcodebuild clean test -workspace LeakDetectorDemo.xcworkspace -scheme LeakDetectorDemo -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcbeautify
        env:
         destination: ${{ matrix.destination }}